In [3]:
import numpy as np
import pandas as pd

In [1]:
from selenium import webdriver
import time
from selenium.webdriver.common.action_chains import ActionChains #move_to_element
import re


#設定driver
path = 'C:\python/chromedriver.exe'
driver = webdriver.Chrome(path)

driver.get('https://shopee.tw/') #到蝦皮網址
time.sleep(1)

#輸入要搜尋的商品
print('輸入商品名稱：')
item = str(input())

#關閉廣告
ads_btn = driver.find_element_by_css_selector('div.shopee-popup__close-btn')
ads_btn.click()

#搜尋商品
t_field = driver.find_element_by_css_selector('input.shopee-searchbar-input__input') #搜尋欄
t_field.send_keys(item)
time.sleep(1)
t_btn = driver.find_element_by_css_selector('button.btn.btn-solid-primary.btn--s.btn--inline') #搜尋按鈕
t_btn.click()

#抓資料
time.sleep(3)
#查詢的資料
dataArr = []
    

def getData():
    index = 0 #第幾個商品
    while(1):
        productArr = []
        try:
            product = driver.find_elements_by_css_selector('div.fBhek2._2xt0JJ')[index] #視窗內的第index個商品
            ActionChains(driver).move_to_element(product).perform() #移動到元素位置


            product_name = product.find_element_by_css_selector('div.yQmmFK._1POlWt._36CEnF').text
            product_price = product.find_element_by_css_selector('div._32hnQt').text
            product_price_r = product_price.split('\n')
            product_sold = product.find_element_by_css_selector('div.go5yPW').text.replace('已售出','')
            
            #print(product_name)

            #if(len(product_price_r) == 1):
                #print(product_price_r[0], end='\n\n')
            #else:
                #print(product_price_r[0] + '-' + product_price_r[1])

            #print(product_sold,end='\n\n' )
            productArr.append(index)
            productArr.append(product_name)
            productArr.append(product_price_r)
            product_sold_new = wordgenerate(product_sold)
            productArr.append(product_sold_new)
            dataArr.append(productArr)
            
            time.sleep(0.1)
            index += 1

        except IndexError:
            break
    print(dataArr)

def wordgenerate(sold):
    if re.findall('萬', sold):
        ger_sold = eval(sold.replace('萬',''))*10000
        return '%d'% ger_sold
        
    else:
        ger_sold2 = sold.replace(',','')
        return ger_sold2
        
#開始
getData()


輸入商品名稱：
手持風扇
[[0, 'SOLOVE N9 手持風扇 送長掛繩 USB手持風扇 隨身風扇 迷你風扇 風扇台扇', ['$399', '$189'], '24000'], [1, '【現貨 免運費！可更換充電電池】手持風扇 隨身風扇 USB風扇 小電扇 靜音風扇 迷你電風扇 桌扇 手拿扇', ['$499', '$99'], '20000'], [2, '🎉防疫專用 解決口罩燜熱 原廠授權 掛脖風扇 2600mAh電池 手持風扇 掛脖小風扇 懶人掛頸隨身攜帶 脖掛風扇', ['$155 - $190'], '37000'], [3, '[免運+發票] 小米有品 VH悠手持風扇 VH悠便攜式手持風扇 小米手持風扇 小米無線 防疫 父親節', ['$399', '$180'], ' 4681'], [4, '【超高CP】USB充電風扇 超低價 充電小風扇 電風扇 簡約大方 風力強勁 清涼一夏 小風扇 出行必備 手持風扇', ['$129', '$99'], '22000'], [5, '【超高CP】USB充電風扇 超低價 充電小風扇 電風扇 簡約大方 風力強勁 清涼一夏 小風扇 出行必備 手持風扇', ['$129', '$99'], '22000'], [6, '【現貨 免運費！可更換充電電池】手持風扇 隨身風扇 USB風扇 小電扇 靜音風扇 迷你電風扇 桌扇 手拿扇', ['$499', '$99'], '20000'], [7, '手持直立式迷你風扇 手持風扇 USB手持風扇 隨身風扇 迷你風扇 風扇台扇 三段風速調節 追劇直立式風扇 台灣現貨', ['$69', '$59'], ' 685'], [8, '{現貨在台🌞每天出貨}頸掛風扇 隨身攜帶 掛脖風扇 電風扇 頸掛風扇 電扇 手持風扇 隨身電風扇 USB風扇 小電風扇', ['$399', '$139'], ' 7561'], [9, '【台灣現貨免運】迷你風扇 夾式風扇 USB充電風扇 靜音電扇 小風扇 手持風扇 迷你 電風扇 小電扇 手持電扇 手持扇', ['$399', '$199'], ' 2657'], [10, '⭐原廠授權⭐夾立式兩用風扇 靜音風扇 可拆式風扇 葉片風扇 USB充電風扇 夾式風扇 調節風扇 小風扇 夾扇 推車風扇', ['$499', '$188'], '13000

In [4]:
dfData = pd.DataFrame(dataArr, columns=['No','ProductName','ProductPrice','ProductSold'])
print(dfData)

    No                                        ProductName    ProductPrice  \
0    0         SOLOVE N9 手持風扇 送長掛繩 USB手持風扇 隨身風扇 迷你風扇 風扇台扇    [$399, $189]   
1    1  【現貨 免運費！可更換充電電池】手持風扇 隨身風扇 USB風扇 小電扇 靜音風扇 迷你電風扇...     [$499, $99]   
2    2  🎉防疫專用 解決口罩燜熱 原廠授權 掛脖風扇 2600mAh電池 手持風扇 掛脖小風扇 懶人...   [$155 - $190]   
3    3  [免運+發票] 小米有品 VH悠手持風扇 VH悠便攜式手持風扇 小米手持風扇 小米無線 防疫...    [$399, $180]   
4    4  【超高CP】USB充電風扇 超低價 充電小風扇 電風扇 簡約大方 風力強勁 清涼一夏 小風扇...     [$129, $99]   
5    5  【超高CP】USB充電風扇 超低價 充電小風扇 電風扇 簡約大方 風力強勁 清涼一夏 小風扇...     [$129, $99]   
6    6  【現貨 免運費！可更換充電電池】手持風扇 隨身風扇 USB風扇 小電扇 靜音風扇 迷你電風扇...     [$499, $99]   
7    7  手持直立式迷你風扇 手持風扇 USB手持風扇 隨身風扇 迷你風扇 風扇台扇 三段風速調節 追...      [$69, $59]   
8    8  {現貨在台🌞每天出貨}頸掛風扇 隨身攜帶 掛脖風扇 電風扇 頸掛風扇 電扇 手持風扇 隨身電...    [$399, $139]   
9    9  【台灣現貨免運】迷你風扇 夾式風扇 USB充電風扇 靜音電扇 小風扇 手持風扇 迷你 電風扇...    [$399, $199]   
10  10  ⭐原廠授權⭐夾立式兩用風扇 靜音風扇 可拆式風扇 葉片風扇 USB充電風扇 夾式風扇 調節風...    [$499, $188]   
11  11  雪花迷你手持小風扇 兩用桌面手持風扇充電usb風扇 充電風扇 迷你小風扇 電風扇 充電扇 迷...     [$210, $59]   

In [9]:
dfData_a = dfData.iloc[0:60,0:3]
dfData_c = dfData.iloc[:,3].astype(int)
dfData_n = pd.concat([dfData_a, dfData_c], axis = 1)
print(dfData_n)

    No                                        ProductName    ProductPrice  \
0    0         SOLOVE N9 手持風扇 送長掛繩 USB手持風扇 隨身風扇 迷你風扇 風扇台扇    [$399, $189]   
1    1  【現貨 免運費！可更換充電電池】手持風扇 隨身風扇 USB風扇 小電扇 靜音風扇 迷你電風扇...     [$499, $99]   
2    2  🎉防疫專用 解決口罩燜熱 原廠授權 掛脖風扇 2600mAh電池 手持風扇 掛脖小風扇 懶人...   [$155 - $190]   
3    3  [免運+發票] 小米有品 VH悠手持風扇 VH悠便攜式手持風扇 小米手持風扇 小米無線 防疫...    [$399, $180]   
4    4  【超高CP】USB充電風扇 超低價 充電小風扇 電風扇 簡約大方 風力強勁 清涼一夏 小風扇...     [$129, $99]   
5    5  【超高CP】USB充電風扇 超低價 充電小風扇 電風扇 簡約大方 風力強勁 清涼一夏 小風扇...     [$129, $99]   
6    6  【現貨 免運費！可更換充電電池】手持風扇 隨身風扇 USB風扇 小電扇 靜音風扇 迷你電風扇...     [$499, $99]   
7    7  手持直立式迷你風扇 手持風扇 USB手持風扇 隨身風扇 迷你風扇 風扇台扇 三段風速調節 追...      [$69, $59]   
8    8  {現貨在台🌞每天出貨}頸掛風扇 隨身攜帶 掛脖風扇 電風扇 頸掛風扇 電扇 手持風扇 隨身電...    [$399, $139]   
9    9  【台灣現貨免運】迷你風扇 夾式風扇 USB充電風扇 靜音電扇 小風扇 手持風扇 迷你 電風扇...    [$399, $199]   
10  10  ⭐原廠授權⭐夾立式兩用風扇 靜音風扇 可拆式風扇 葉片風扇 USB充電風扇 夾式風扇 調節風...    [$499, $188]   
11  11  雪花迷你手持小風扇 兩用桌面手持風扇充電usb風扇 充電風扇 迷你小風扇 電風扇 充電扇 迷...     [$210, $59]   

In [12]:
df = dfData_n.sort_values(by ='ProductSold', axis = 0, ascending=False)
print(df)

    No                                        ProductName    ProductPrice  \
2    2  🎉防疫專用 解決口罩燜熱 原廠授權 掛脖風扇 2600mAh電池 手持風扇 掛脖小風扇 懶人...   [$155 - $190]   
0    0         SOLOVE N9 手持風扇 送長掛繩 USB手持風扇 隨身風扇 迷你風扇 風扇台扇    [$399, $189]   
4    4  【超高CP】USB充電風扇 超低價 充電小風扇 電風扇 簡約大方 風力強勁 清涼一夏 小風扇...     [$129, $99]   
5    5  【超高CP】USB充電風扇 超低價 充電小風扇 電風扇 簡約大方 風力強勁 清涼一夏 小風扇...     [$129, $99]   
1    1  【現貨 免運費！可更換充電電池】手持風扇 隨身風扇 USB風扇 小電扇 靜音風扇 迷你電風扇...     [$499, $99]   
6    6  【現貨 免運費！可更換充電電池】手持風扇 隨身風扇 USB風扇 小電扇 靜音風扇 迷你電風扇...     [$499, $99]   
10  10  ⭐原廠授權⭐夾立式兩用風扇 靜音風扇 可拆式風扇 葉片風扇 USB充電風扇 夾式風扇 調節風...    [$499, $188]   
28  28  🔥拚全台最低價🔥夾式風扇 可拆式電風扇 隨身電風扇可換電池 USB充電 攜帶式 車用 嬰兒車...   [$139 - $195]   
59  59  宏晉 HongJin Z1復古掛脖風扇 桌面+手持+隨身三用小風扇 三段風速 小巧不占空間 ...    [$399, $149]   
8    8  {現貨在台🌞每天出貨}頸掛風扇 隨身攜帶 掛脖風扇 電風扇 頸掛風扇 電扇 手持風扇 隨身電...    [$399, $139]   
38  38  贈手持風扇 几素 超涼大風量 無葉風扇 頸掛風扇 掛脖風扇 懶人風扇 迷你風扇 運動風扇 U...  [$1,880, $688]   
31  31  🎉現貨免運🔥買一送三🔥熱賣頸掛風扇 掛脖子懶人運動風扇 迷你懶人風扇掛脖子風扇 充電掛脖US...    [$350, $185]   

### 將資料依銷售量分為三個labels

In [16]:
def ConvertLabel(score):
  if score >= 1000:
    return 'Good'
  
  elif 999 >= score >= 500:
    return 'Not Bad'
  
  else:
    return 'Bad'

def Convert(data):
  data['label'] = data['ProductSold'].map(lambda e : ConvertLabel(e))
  data = data[data['label'].isin(['Good','Not Bad','Bad'])]
  #data['label'] = data['label'].replace({'Good':2, 'Not Bad':1, 'Bad':0})
  return data

Convert(df)

No                                        ProductName    ProductPrice  \
2    2  🎉防疫專用 解決口罩燜熱 原廠授權 掛脖風扇 2600mAh電池 手持風扇 掛脖小風扇 懶人...   [$155 - $190]   
0    0         SOLOVE N9 手持風扇 送長掛繩 USB手持風扇 隨身風扇 迷你風扇 風扇台扇    [$399, $189]   
4    4  【超高CP】USB充電風扇 超低價 充電小風扇 電風扇 簡約大方 風力強勁 清涼一夏 小風扇...     [$129, $99]   
5    5  【超高CP】USB充電風扇 超低價 充電小風扇 電風扇 簡約大方 風力強勁 清涼一夏 小風扇...     [$129, $99]   
1    1  【現貨 免運費！可更換充電電池】手持風扇 隨身風扇 USB風扇 小電扇 靜音風扇 迷你電風扇...     [$499, $99]   
6    6  【現貨 免運費！可更換充電電池】手持風扇 隨身風扇 USB風扇 小電扇 靜音風扇 迷你電風扇...     [$499, $99]   
10  10  ⭐原廠授權⭐夾立式兩用風扇 靜音風扇 可拆式風扇 葉片風扇 USB充電風扇 夾式風扇 調節風...    [$499, $188]   
28  28  🔥拚全台最低價🔥夾式風扇 可拆式電風扇 隨身電風扇可換電池 USB充電 攜帶式 車用 嬰兒車...   [$139 - $195]   
59  59  宏晉 HongJin Z1復古掛脖風扇 桌面+手持+隨身三用小風扇 三段風速 小巧不占空間 ...    [$399, $149]   
8    8  {現貨在台🌞每天出貨}頸掛風扇 隨身攜帶 掛脖風扇 電風扇 頸掛風扇 電扇 手持風扇 隨身電...    [$399, $139]   
38  38  贈手持風扇 几素 超涼大風量 無葉風扇 頸掛風扇 掛脖風扇 懶人風扇 迷你風扇 運動風扇 U...  [$1,880, $688]   
31  31  🎉現貨免運🔥買一送三🔥熱賣頸掛風扇 掛脖子懶人運動風扇 迷你懶人風扇掛脖子風扇 充電掛脖US...    [$350, $185]   
3    3  [免運+發票] 小米有品 VH悠手持風扇 VH悠便攜式手持風扇 小米手持風扇 小米無線 防疫...    [$399, $180]   
55  55  宏晉 HongJin Z2 手持風扇 桌上+手持兩用設計 USB充電式風扇 三吋扇葉 可以自...     [$199, $89]   
9    9  【台灣現貨免運】迷你風扇 夾式風扇 USB充電風扇 靜音電扇 小風扇 手持風扇 迷你 電風扇...    [$399, $199]   
27  27  【升級版2600mAh】掛脖小風扇 脖掛風扇 掛頸 免持兩用 隨身風扇 懶人風扇 迷你風扇 ...   [$235 - $319]   
48  48  鴻嘉源 USB手持桌面兩用風扇 韓國熱銷款充電立式風扇 小風扇 隨身風扇 手持風扇 桌面風扇...    [$799, $299]   
36  36  共田 暴風版 外出風扇 口袋風扇 芭蕉扇 共田風扇 充電 USB風扇 風扇 電風扇 迷你風扇...          [$180]   
46  46  【台灣現貨】頸掛電扇 掛脖風扇 脖掛風扇 無叶風扇 懶人風扇 迷你風扇 運動風扇 掛脖小風扇...    [$299, $259]   
14  14  【台灣現貨含發票】 手持 三腳架 支架 風扇 小風扇 手持風扇 三角架風扇 隨身風扇 旅行風...    [$380, $199]   
35  35  【台灣現貨】掛脖風扇 頸掛電扇 脖掛風扇 便捷式迷你隨身usb充電風扇 懶人風扇 迷你風扇 ...    [$399, $329]   
24  24  台灣現貨 折疊小風扇 折疊風扇 掛脖風扇 掛脖小風扇 手持小風扇 隨身風扇 掛脖電扇 可當行...   [$143 - $158]   
53  53  台灣出貨兩天到貨！靜音大風力風扇折疊伸縮風扇 遠端紅外線遙控usb充電便攜宿舍大風力電扇 P...          [$499]   
18  18  【台灣出貨免運！可放置手機+更換電池】USB風扇 電風扇 手持風扇 迷你電風扇 手持小風扇 ...    [$188, $135]   
44  44  折疊桌上 復古 文青 迷你掛脖風扇 掛脖 風扇 USB風扇 手持風扇 桌扇 掛扇 夏天風扇 ...   [$199 - $299]   
41  41  【迷你好帶🎈】夾子風扇 迷你風扇 隨身風扇 便攜風扇 夾式風扇 可愛風扇 外出小風扇 360...    [$359, $219]   
47  47  [台灣發貨]八吋 桌上型摺疊風扇 送2電池 可充電風扇 隨身風扇 大風扇 三段風量 立扇 桌...   [$199 - $308]   
7    7  手持直立式迷你風扇 手持風扇 USB手持風扇 隨身風扇 迷你風扇 風扇台扇 三段風速調節 追...      [$69, $59]   
56  56  關注折20元 可調式45度攜帶式風扇 小風扇 Usb風扇 隨身風扇 立扇 手風扇 Usb充電...    [$299, $179]   
25  25  USB夾式旋轉風扇 夾式電風扇 桌上型風扇 超高品質 靜音 大風量風扇 360度轉轉風扇 迷...    [$210, $159]   
20  20  繽紛馬卡龍色 掛脖風扇 手持風扇 USB充電涼感扇 桌面小立扇 口袋迷你風扇 懶人折疊扇 掛...    [$500, $249]   
23  23     高檔手持電風扇 手持風扇 迷你 便攜 簡約香薰風扇 三擋風力 清新小風扇 清涼一夏 時尚美觀   [$239 - $259]   
15  15  USB小夜燈夾子風扇 推車風扇 嬰兒車風扇 電風扇 電扇 夾扇 立扇 桌扇 手持風扇 夾式迷...    [$249, $139]   
19  19  【現貨】折疊小風扇 掛脖風扇 手持電風扇 手機支架風扇USB充電 掛頸風扇 頸掛運動風扇 桌...          [$189]   
17  17  韓版 二合一手持風扇【手機批發網】送線+掛繩 手持 桌用 USB風扇 嬰兒車 立式 夾式 電...     [$35 - $99]   
58  58  【台灣現貨】小米有品 紫米 ZMI 隨身手持風扇 3350mAh 便攜手拿風扇 桌面小電扇 ...    [$359, $299]   
45  45  🌱買10送1🌱現貨 手持風扇 掛脖風扇 掛脖小風扇 懶人掛頸 便攜 隨身攜帶 usb充電 掛...          [$139]   
33  33  相機造型掛脖風扇 相機造型風扇 迷你電風扇 隨身電風扇 掛脖子風扇 手持風扇 頸掛風扇 迷你...    [$399, $179]   
42  42  【現貨 免運費 24H出貨】韓國爆款液晶顯示掛脖風扇 迷你小風扇 隨身風扇 涼風扇 小風扇 ...    [$499, $249]   
52  52  【正貨免運】 几素 超涼大風量 無葉風扇 頸掛風扇 掛脖風扇 懶人風扇 迷你風扇 運動風扇 ...    [$688, $619]   
12  12  頸掛摺疊風扇 適用居家/外出/夏日 掛脖風扇 頸掛風扇 手持風扇 電風扇 充電風扇 桌面風扇...     [$259, $99]   
54  54  【台灣出貨!免運 復古桌面風扇】USB 充電風扇 電風扇 小風扇 冷風扇 循環扇 立扇 靜音...    [$999, $335]   
39  39  【免運券免費送】折疊式風扇 4吋 手持風扇 小風扇 隨身風扇 桌上型風扇 usb充電 桌上風...    [$299, $139]   
40  40  電量顯示掛脖風扇 手持電扇 懶人風扇 掛脖風扇 USB風扇 隨身風扇 頸掛風扇 風扇 手持風...    [$899, $199]   
11  11  雪花迷你手持小風扇 兩用桌面手持風扇充電usb風扇 充電風扇 迷你小風扇 電風扇 充電扇 迷...     [$210, $59]   
43  43  風扇 電扇 立扇 涼風扇 台灣製 12吋電風扇 360度 直立電風扇 立扇三檔調速 高風速低...    [$999, $499]   
50  50  台灣出貨 頸掛式 掛脖小風扇 3000mah 折疊風扇 手持風扇 三檔 摺疊扇 頸掛風扇 便...    [$500, $199]   
32  32  4吋 USB充電 無印風 輕巧攜帶 收納式 伸縮 折疊風扇 風扇 野餐 露營風扇 隨身風扇 ...    [$650, $199]   
51  51  手持風扇 usb風扇 無葉風扇 無葉片USB充電手持風扇【台灣現貨滿額免運】關注我們現領折價...    [$179, $129]   
49  49  【SPeed-快速出貨】夜光小風扇 迷你電風扇 嬰兒車風扇 迷你小風扇 夾式風扇 小夜燈 小...    [$349, $139]   
57  57  《高續航│雙馬達雙葉│吹得涼》現貨 手持風扇 雙葉風扇 四檔調速 USB風扇 小風扇 風扇【...          [$199]   


### 運用jieba套件做分詞

In [14]:
import jieba.posseg as pseg

def jieba_tokenizer(text):
  words = pseg.cut(text)
  return ' '.join([word for word,flag in words if flag != 'x'])

df['Product_tokenized'] = df.loc[:,'ProductName'].apply(jieba_tokenizer)

print(df.iloc[:,[0,5]])

Building prefix dict from the default dictionary ...
Dumping model to file cache C:\Users\Becky\AppData\Local\Temp\jieba.cache
Loading model cost 1.287 seconds.
Prefix dict has been built successfully.


    No                                  Product_tokenized
2    2  防疫 專用 解決 口罩 燜 熱 原廠 授權 掛 脖風 扇 2600 mAh 電池 手持 風扇...
0    0  SOLOVE N9 手持 風扇 送長 掛 繩 USB 手持 風扇 隨身 風扇 迷你 風扇 風...
4    4  超高 CP USB 充電 風扇 超低 價 充電 小 風扇 電風 扇 簡約 大方 風力 強勁 ...
5    5  超高 CP USB 充電 風扇 超低 價 充電 小 風扇 電風 扇 簡約 大方 風力 強勁 ...
1    1  現貨 免 運費 可 更 換充 電電池 手持 風扇 隨身 風扇 USB 風扇 小 電扇 靜音 ...
6    6  現貨 免 運費 可 更 換充 電電池 手持 風扇 隨身 風扇 USB 風扇 小 電扇 靜音 ...
10  10  原廠 授權 夾 立式 兩 用 風扇 靜音 風扇 可拆 式 風扇 葉片 風扇 USB 充電 風...
28  28  拚全 台 最低 價 夾式 風扇 可拆 式 電風 扇 隨 身電 風扇 可換 電池 USB 充電...
59  59  宏晉 HongJin Z1 復 古 掛 脖 風 扇 桌面 手持 隨身 三 用 小 風扇 三段...
8    8  現貨 在 台 每天 出貨 頸 掛 風扇 隨身 攜帶 掛 脖風 扇 電風 扇 頸 掛 風扇 電...
38  38  手持 風扇 几素 超 涼大 風量 無葉 風扇 頸 掛 風扇 掛 脖風 扇 懶 人 風扇 迷你...
31  31  現貨 免運 買 一 送 三 熱 賣 頸 掛 風扇 掛 脖子 懶人 運動 風扇 迷你 懶 人 ...
3    3  免運 發票 小米 有品 VH 悠 手持 風扇 VH 悠便 攜式 手持 風扇 小米 手持 風扇...
55  55  宏晉 HongJin Z2 手持 風扇 桌上 手持 兩 用 設計 USB 充電式 風扇 三 ...
9    9  台灣 現貨 免運 迷你 風扇 夾式 風扇 USB 充電 風扇 靜音 電扇 小 風扇 手持 風...
27  27  升級 版 2600 mAh 掛 脖小 風扇 脖掛 風扇 掛 頸 免持 兩 用 隨身 風扇 懶...
48  48  鴻嘉源 US

### 將文本轉成數字序列

In [15]:
from keras.preprocessing.text import Tokenizer

MAX_NUM_WORDS = 1000
tokenizer = Tokenizer(num_words = MAX_NUM_WORDS)

sentences = df['Product_tokenized'].apply(str).tolist()
tokenizer.fit_on_texts(sentences)
x_train = tokenizer.texts_to_sequences(sentences)
print(len(x_train))
print(x_train[:1])

60
[[81, 150, 151, 152, 153, 82, 83, 84, 3, 12, 2, 85, 50, 38, 4, 1, 3, 22, 1, 15, 16, 3, 11, 9, 23, 51, 1]]


In [17]:
for seq in x_train[:9]:
  print([tokenizer.index_word[idx] for idx in seq])

['防疫', '專用', '解決', '口罩', '燜', '熱', '原廠', '授權', '掛', '脖風', '扇', '2600', 'mah', '電池', '手持', '風扇', '掛', '脖小', '風扇', '懶', '人', '掛', '頸', '隨身', '攜帶', '脖掛', '風扇']
['solove', 'n9', '手持', '風扇', '送長', '掛', '繩', 'usb', '手持', '風扇', '隨身', '風扇', '迷你', '風扇', '風扇', '台扇']
['超高', 'cp', 'usb', '充電', '風扇', '超低', '價', '充電', '小', '風扇', '電風', '扇', '簡約', '大方', '風力', '強勁', '清涼', '一', '夏', '小', '風扇', '出行', '必備', '手持', '風扇']
['超高', 'cp', 'usb', '充電', '風扇', '超低', '價', '充電', '小', '風扇', '電風', '扇', '簡約', '大方', '風力', '強勁', '清涼', '一', '夏', '小', '風扇', '出行', '必備', '手持', '風扇']
['現貨', '免', '運費', '可', '更', '換充', '電電池', '手持', '風扇', '隨身', '風扇', 'usb', '風扇', '小', '電扇', '靜音', '風扇', '迷你', '電風', '扇', '桌扇', '手', '拿', '扇']
['現貨', '免', '運費', '可', '更', '換充', '電電池', '手持', '風扇', '隨身', '風扇', 'usb', '風扇', '小', '電扇', '靜音', '風扇', '迷你', '電風', '扇', '桌扇', '手', '拿', '扇']
['原廠', '授權', '夾', '立式', '兩', '用', '風扇', '靜音', '風扇', '可拆', '式', '風扇', '葉片', '風扇', 'usb', '充電', '風扇', '夾式', '風扇', '調節', '風扇', '小', '風扇', '夾扇', '推車', '風扇']
['拚全', '台', '最低', '價

### 序列的 Zero Padding
因為發現每個商品文字的序列長度並不相同

In [18]:
for seq in x_train[:10]:
  print(len(seq), seq[:5],'.....')

27 [81, 150, 151, 152, 153] .....
16 [154, 155, 4, 1, 156] .....
25 [58, 88, 5, 10, 1] .....
25 [58, 88, 5, 10, 1] .....
24 [14, 40, 63, 64, 94] .....
24 [14, 40, 63, 64, 94] .....
26 [83, 84, 157, 66, 41] .....
27 [159, 69, 160, 59, 19] .....
26 [103, 104, 165, 31, 32] .....
28 [14, 170, 69, 171, 27] .....


In [20]:
#最長有31個序列
max_seq_len = max([len(seq) for seq in x_train])
print(max_seq_len)

31


In [21]:
#將所有的序列長度都設為30

import keras
from keras.preprocessing.sequence import pad_sequences
MAX_SEQUENCE_LENGTH = 30
x_train = keras.preprocessing.sequence.pad_sequences(x_train, maxlen = MAX_SEQUENCE_LENGTH)

print(x_train[0])

[  0   0   0  81 150 151 152 153  82  83  84   3  12   2  85  50  38   4
   1   3  22   1  15  16   3  11   9  23  51   1]


In [22]:
for seq in x_train:
  assert len(seq) == 30
print('所有標題的序列長度皆為30!')

所有標題的序列長度皆為30!


## label的處理

In [23]:

import numpy as np

#定義每一個分類對應到的數字
label_to_index = {
    'Good': 2,
    'Not Bad': 1,
    'Bad': 0
}

#將分類標籤對應到剛定義的數字

y_train = df.label.apply(lambda x: label_to_index[x])

y_train = np.asarray(y_train).astype('float32')

print(y_train[:5])

[2. 2. 2. 2. 2.]


### 做 one hot encoding

In [24]:
from keras.utils import np_utils

y_train = np_utils.to_categorical(y_train)

print(y_train[:5])

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [25]:
#用 tokenizer 裡頭的字典 index_word 還原文本看看：
for i, seq in enumerate(x_train[:5]):
  print(f'商品名稱{i + 1}:')
  print([tokenizer.index_word.get(idx,'')for idx in seq])
  print()

商品名稱1:
['', '', '', '防疫', '專用', '解決', '口罩', '燜', '熱', '原廠', '授權', '掛', '脖風', '扇', '2600', 'mah', '電池', '手持', '風扇', '掛', '脖小', '風扇', '懶', '人', '掛', '頸', '隨身', '攜帶', '脖掛', '風扇']

商品名稱2:
['', '', '', '', '', '', '', '', '', '', '', '', '', '', 'solove', 'n9', '手持', '風扇', '送長', '掛', '繩', 'usb', '手持', '風扇', '隨身', '風扇', '迷你', '風扇', '風扇', '台扇']

商品名稱3:
['', '', '', '', '', '超高', 'cp', 'usb', '充電', '風扇', '超低', '價', '充電', '小', '風扇', '電風', '扇', '簡約', '大方', '風力', '強勁', '清涼', '一', '夏', '小', '風扇', '出行', '必備', '手持', '風扇']

商品名稱4:
['', '', '', '', '', '超高', 'cp', 'usb', '充電', '風扇', '超低', '價', '充電', '小', '風扇', '電風', '扇', '簡約', '大方', '風力', '強勁', '清涼', '一', '夏', '小', '風扇', '出行', '必備', '手持', '風扇']

商品名稱5:
['', '', '', '', '', '', '現貨', '免', '運費', '可', '更', '換充', '電電池', '手持', '風扇', '隨身', '風扇', 'usb', '風扇', '小', '電扇', '靜音', '風扇', '迷你', '電風', '扇', '桌扇', '手', '拿', '扇']



### 切割訓練資料集 & 驗證資料集

In [26]:
from sklearn.model_selection import train_test_split

Validation_ratio = 0.2
Random_State = 50

x_train, x_val ,y_train, y_val = train_test_split(
    x_train,y_train,
    test_size = Validation_ratio,
    random_state = Random_State
)

print("Training Set")
print("-" * 10)
print(f"x_train: {x_train.shape}")
print(f"y_train : {y_train.shape}")

print("-" * 10)
print(f"x_val:   {x_val.shape}")
print(f"y_val :   {y_val.shape}")
print("-" * 10)
print("Test Set")

Training Set
----------
x_train: (48, 30)
y_train : (48, 3)
----------
x_val:   (12, 30)
y_val :   (12, 3)
----------
Test Set


### 將一個詞彙或句子轉換成一個實數詞向量（Vectors of real numbers）的技術被稱之為詞嵌入（Word Embedding）

In [27]:
from keras import layers
from keras.layers import Embedding, LSTM, concatenate, Dense, Input
from keras.models import Model

# 基本參數設置，有幾個分類
NUM_CLASSES = 3

# 在語料庫裡有多少詞彙
MAX_NUM_WORDS = 1000

# 一個標題最長有幾個詞彙
MAX_SEQUENCE_LENGTH = 30

# 一個詞向量的維度
NUM_EMBEDDING_DIM = 256

# LSTM 輸出的向量維度
NUM_LSTM_UNITS = 128

x_input = Input(shape = (30, ), dtype = 'int32')

#詞嵌入層
embedding_layer = layers.Embedding(MAX_NUM_WORDS, NUM_EMBEDDING_DIM)
x_embedded = embedding_layer(x_input)

#LSTM層
lstm = LSTM(NUM_LSTM_UNITS)
x_output = lstm(x_embedded)

#全連接層
dense = Dense(
    units = NUM_CLASSES,
    activation = 'softmax')
predictions = dense(x_output)

#model
model = Model(
    inputs = x_input,
    outputs = predictions
)

model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 30)]              0         
_________________________________________________________________
embedding (Embedding)        (None, 30, 256)           256000    
_________________________________________________________________
lstm (LSTM)                  (None, 128)               197120    
_________________________________________________________________
dense (Dense)                (None, 3)                 387       
Total params: 453,507
Trainable params: 453,507
Non-trainable params: 0
_________________________________________________________________


In [28]:
x_train[:10].shape

(10, 30)

In [29]:
model.compile(
    optimizer = 'rmsprop',
    loss = 'categorical_crossentropy',
    metrics = ['accuracy']
)

history = model.fit(
    x = x_train,
    y = y_train,
    batch_size = 10,
    epochs = 10,
    validation_data = (x_val, y_val),
    shuffle = True
)

Epoch 1/10
5/5 [==============================] - 23s 294ms/step - loss: 1.0814 - accuracy: 0.3319 - val_loss: 1.0427 - val_accuracy: 0.4167
Epoch 2/10
5/5 [==============================] - 0s 31ms/step - loss: 1.0101 - accuracy: 0.5542 - val_loss: 1.0560 - val_accuracy: 0.4167
Epoch 3/10
5/5 [==============================] - 0s 35ms/step - loss: 0.9122 - accuracy: 0.5722 - val_loss: 1.2064 - val_accuracy: 0.4167
Epoch 4/10
5/5 [==============================] - 0s 33ms/step - loss: 0.6695 - accuracy: 0.7514 - val_loss: 1.0645 - val_accuracy: 0.2500
Epoch 5/10
5/5 [==============================] - 0s 36ms/step - loss: 0.6378 - accuracy: 0.8792 - val_loss: 1.1038 - val_accuracy: 0.2500
Epoch 6/10
5/5 [==============================] - 0s 37ms/step - loss: 0.5953 - accuracy: 0.9514 - val_loss: 1.0733 - val_accuracy: 0.3333
Epoch 7/10
5/5 [==============================] - 0s 34ms/step - loss: 0.3305 - accuracy: 0.9417 - val_loss: 2.5826 - val_accuracy: 0.4167
Epoch 8/10
5/5 [=========

In [30]:
test_csv = 'C:\python/scrapy_fan2.csv'
test = pd.read_csv(test_csv, index_col= 0 ,encoding='utf-8')
print(test.head())

    No                                        ProductName      ProductPrice  \
46  46  🎉防疫專用 解決口罩燜熱 原廠授權 掛脖風扇 2600mAh電池 手持風扇 掛脖小風扇 懶人...   ['$155 - $190']   
0    0         SOLOVE N9 手持風扇 送長掛繩 USB手持風扇 隨身風扇 迷你風扇 風扇台扇  ['$399', '$249']   
5    5         SOLOVE N9 手持風扇 送長掛繩 USB手持風扇 隨身風扇 迷你風扇 風扇台扇  ['$399', '$249']   
47  47  【超高CP】USB充電風扇 超低價 充電小風扇 電風扇 簡約大方 風力強勁 清涼一夏 小風扇...   ['$129', '$99']   
8    8  【超高CP】USB充電風扇 超低價 充電小風扇 電風扇 簡約大方 風力強勁 清涼一夏 小風扇...   ['$129', '$99']   

    ProductSold  
46        34000  
0         23000  
5         23000  
47        22000  
8         22000  


In [31]:
test['product2_tokenized'] = test.loc[:,'ProductName'].apply(jieba_tokenizer)

x_test = tokenizer.texts_to_sequences(test.product2_tokenized)

#zero padding
x_test = keras.preprocessing.sequence.pad_sequences(x_test, maxlen = MAX_SEQUENCE_LENGTH)
predictions = model.predict(x_test)
predictions[:5]

array([[0.21561964, 0.20214993, 0.5822304 ],
       [0.14576738, 0.6412469 , 0.21298574],
       [0.14576738, 0.6412469 , 0.21298574],
       [0.02856758, 0.00997464, 0.96145785],
       [0.02856758, 0.00997464, 0.96145785]], dtype=float32)